codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths:
          - "tests/"
        target: 90%
      source:
        paths:
          - "opf/"
        target: 98%
        threshold: 0.002
    patch:
      default:
        target: 80%  # new contributions should hav