name: Unit Test
on: [pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install IPOPT & Python in Conda
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          conda install ipopt python=${{matrix.python}} -c conda-forge 
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pip install pytest-cov
          python -m pytest -s -v --cov=./tests --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3