name: Unit Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Create Conda Environment
        run: |
          conda create -n env${{matrix.python}} python=${{matrix.python}}
      - name: Activate Conda Environment
        run: |
          conda activate env${{matrix.python}}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Install IPOPT
        run: |
          conda install ipopt -c conda-forge 
      - name: Run Pytest
        run: |
          pip install pytest-cov
          python -m pytest -s -v --cov=./tests --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3