name: Unit Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install -e .
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pip install pytest-cov
          python -m pytest -s -v --cov=./tests --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3